language: java
jdk: openjdk11
cache:
  directories:
    - $HOME/.m2

deploy:
  provider: script
  skip_cleanup: true
  script: mvn --settings .travis/settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V deploy
