language: java
jdk: openjdk11
cache:
  directories:
    - $HOME/.m2

before_install:
  - source install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
  - cp .travis/settings.xml $HOME/.m2/settings.xml

deploy:
  provider: script
  skip_cleanup: true
  script: mvn -DskipTests=true -Dmaven.javadoc.skip=true -B -V deploy
