package com.avereon.util;

import lombok.CustomLog;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Random;

@CustomLog
public class IdGenerator {

	private static final Random RANDOM = new Random();

	// The character map must contain 16 characters, no more, no less
	// List of consonant letters with no descenders in no particular order
	private static final char[] map = "mhnflcdtvkxzrwbs".toCharArray();

	public static String getId() {
		return getId( System.currentTimeMillis() ^ RANDOM.nextLong() );
	}

	public static String getId( long value ) {
		StringBuilder builder = new StringBuilder();

		for( int count = 0; count < 16; count++ ) {
			builder.append( map[ (int)(value & 0xF) ] );
			value >>= 4;
		}

		return builder.toString();
	}

	public static String getId( String string ) {
		long id = 0;

		try {
			MessageDigest digest = MessageDigest.getInstance( "SHA-256" );
			byte[] hash = digest.digest( string.getBytes( StandardCharsets.UTF_8 ) );
			for( int index = 0; index < hash.length; index++ ) {
				long value = hash[ index ];
				value = value << (index % 8 * 8);
				id ^= value;
			}
		} catch( Exception exception ) {
			log.atSevere().withCause( exception ).log( "Error computing id for: %s", string );
		}

		return getId( id );
	}

	/**
	 * Convert an integer value to a slug. A slug is the string of characters
	 * generated by replacing the 4-bit nibbles of the value with characters.
	 * A 32-bit integer will generate an 8-character slug.
	 *
	 * @param value The integer value
	 * @return The slug
	 */
	public static String slug( int value ) {
		StringBuilder builder = new StringBuilder();

		for( int count = 0; count < 8; count++ ) {
			builder.append( map[ value & 0xF ] );
			value >>= 4;
		}

		return builder.toString();
	}

	/**
	 * Convert a long value to a slug. The slug for a long value is generated
	 * by converting the long value to an integer value,  using
	 * {@link Long#hashCode(long)}, and then converting the integer value to a
	 * slug.
	 *
	 * @param value The long value
	 * @return The slug
	 */
	public static String slug( long value ) {
		return slug( Long.hashCode( value ) );
	}

}
