name: Avereon Zevra Library

on: [push]
#  push:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: echo "HELLO" && echo ${AVN_REPO_USERNAME} && echo HELLO
#        run: mvn deploy -B -U -V --settings .github/settings.xml --file pom.xml
